/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productos;

import javax.swing.JOptionPane;

/**
 *
 * @author sebastian salamanca
 */
public class producto extends javax.swing.JFrame {

   prod lapiz, aspirina, borrador,pan;
   int l=0,a=0,b=0,p=0;
   float ingresos;
    public producto() {
        initComponents();
         lapiz=new prod();
         aspirina=new prod();
         borrador=new prod();
         pan=new prod();
        lapiz.setNombre(l1.getText());
        lapiz.setCant(Integer.parseInt(l5.getText()));
        lapiz.setPrecio(Float.parseFloat(l13.getText()));
        lapiz.setIVA((float) 0.16);
        
        aspirina.setNombre(l2.getText());
        aspirina.setCant(Integer.parseInt(l6.getText()));
        aspirina.setPrecio(Float.parseFloat(l14.getText()));
        aspirina.setIVA((float) 0.12);
        
        borrador.setNombre(l3.getText());
        borrador.setCant(Integer.parseInt(l7.getText()));
        borrador.setPrecio(Float.parseFloat(l15.getText()));
        borrador.setIVA((float) 0.16);
        
        pan.setNombre(l4.getText());
        pan.setCant(Integer.parseInt(l8.getText()));
        pan.setPrecio(Float.parseFloat(l16.getText()));
        pan.setIVA((float) 0.04);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        l17.setText("producto");

        l18.setText("cantidad");

        l19.setText("IVA");

        l20.setText("precio");

        l1.setText("Lapiz");

        l2.setText("Aspirina");

        l3.setText("Borrador");

        l4.setText("Pan");

        l5.setText("18");

        l6.setText("25");

        l7.setText("30");

        l8.setText("15");

        l9.setText("16.0%");

        l10.setText("12.0%");

        l11.setText("16.0%");

        l12.setText("4.0%");

        l13.setText("550.0");

        l14.setText("109.5");

        l15.setText("207.3");

        l16.setText("150.0");

        jButton1.setText("Vender Productos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        b2.setText("Pedir Productos");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresos");

        jLabel2.setText("Producto mas vendido");

        jLabel3.setText("Producto menos vendido");

        l21.setText("0");

        l22.setText(".");

        l23.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(l17)
                                    .addComponent(l1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(l4)
                                        .addComponent(l3)))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(l18)
                                            .addComponent(l5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(l10, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(l9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(l11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(l12, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(l19)
                                                .addGap(13, 13, 13))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(l7)
                                            .addComponent(l6)
                                            .addComponent(l8))
                                        .addGap(99, 99, 99)))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l13)
                                    .addComponent(l20)
                                    .addComponent(l14)
                                    .addComponent(l15)
                                    .addComponent(l16)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(l23)
                                .addComponent(b2)
                                .addComponent(l22)
                                .addComponent(l21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l17)
                    .addComponent(l18)
                    .addComponent(l19)
                    .addComponent(l20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l5)
                        .addComponent(l9)
                        .addComponent(l13))
                    .addComponent(l1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l6)
                        .addComponent(l10)
                        .addComponent(l14))
                    .addComponent(l2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l3)
                    .addComponent(l7)
                    .addComponent(l11)
                    .addComponent(l15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l4)
                    .addComponent(l8)
                    .addComponent(l12)
                    .addComponent(l16))
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(l21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(l22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(l23))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float total;
        String prod=JOptionPane.showInputDialog("Que producto desea comprar");
       if(prod.equals("lapiz")){
           int cant=Integer.parseInt(JOptionPane.showInputDialog("Cantidad"));
           lapiz.setCant(lapiz.getCant()-cant);
           l5.setText(String.valueOf(lapiz.getCant()));
           total=(lapiz.getPrecio()*cant)+(lapiz.getPrecio()*cant*lapiz.getIVA());
           ingresos+=total;
           l21.setText(String.valueOf(ingresos));
           l+=cant;
       }
       if(prod.equals("aspirina")){
           int cant=Integer.parseInt(JOptionPane.showInputDialog("Cantidad"));
           aspirina.setCant(aspirina.getCant()-cant);
           l6.setText(String.valueOf(aspirina.getCant()));
           total=(aspirina.getPrecio()*cant)+(aspirina.getPrecio()*cant*aspirina.getIVA());
           ingresos+=total;
           l21.setText(String.valueOf(ingresos));
           a+=cant;
       }
       if(prod.equals("borrador")){
           int cant=Integer.parseInt(JOptionPane.showInputDialog("Cantidad"));
           borrador.setCant(borrador.getCant()-cant);
           l7.setText(String.valueOf(borrador.getCant()));
           total=(borrador.getPrecio()*cant)+(borrador.getPrecio()*cant*borrador.getIVA());
           ingresos+=total;
           l21.setText(String.valueOf(ingresos));
           b+=cant;
       }
       if(prod.equals("pan")){
           int cant=Integer.parseInt(JOptionPane.showInputDialog("Cantidad"));
           pan.setCant(pan.getCant()-cant);
           l8.setText(String.valueOf(pan.getCant()));
           total=(pan.getPrecio()*cant)+(pan.getPrecio()*cant*pan.getIVA());
           ingresos+=total;
           l21.setText(String.valueOf(ingresos));
           p+=cant;
       }
       
       
       if(l>=a && l>=b && l>=p){
           l22.setText(lapiz.getNombre());
       }else if(a>=l && a>=b&& a>=p){
           l22.setText(aspirina.getNombre());
       }else if(b>=a && b>=l&& b>=p){
           l22.setText(borrador.getNombre());
       }else if(p>=a && p>=b&& p>=l){
           l22.setText(pan.getNombre());
       }
       
       if(l<=a && l<=b&& l<=p){
           l23.setText(lapiz.getNombre());
       }else if(a<=l && a<=b&& a<=p){
           l23.setText(aspirina.getNombre());
       }else if(b<=a && b<=l&& b<=p){
           l23.setText(borrador.getNombre());
       }else if(p<=a && p<=b&& p<=l){
           l23.setText(pan.getNombre());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        String prod=JOptionPane.showInputDialog("Que producto desea pedir");
       if(prod.equals("lapiz")){
           int cant=Integer.parseInt(JOptionPane.showInputDialog("Cantidad"));
           lapiz.setCant(lapiz.getCant()+cant);
           l5.setText(String.valueOf(lapiz.getCant()));
   
       }
       if(prod.equals("aspirina")){
           int cant=Integer.parseInt(JOptionPane.showInputDialog("Cantidad"));
           aspirina.setCant(aspirina.getCant()+cant);
           l6.setText(String.valueOf(aspirina.getCant()));
          
       }
       if(prod.equals("borrador")){
           int cant=Integer.parseInt(JOptionPane.showInputDialog("Cantidad"));
           borrador.setCant(borrador.getCant()+cant);
           l7.setText(String.valueOf(borrador.getCant()));
          
       }
       if(prod.equals("pan")){
           int cant=Integer.parseInt(JOptionPane.showInputDialog("Cantidad"));
           pan.setCant(pan.getCant()+cant);
           l8.setText(String.valueOf(pan.getCant()));
           
       }
       
    }//GEN-LAST:event_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
